<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_chimneys_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>fff53459-03d3-4fea-b6a1-92d41e03c288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq254CEQY9bu4WIGlwebnp06SWkVtvJ7rYHwfV3eTdb3lu3WualFDJKkrn9a01KM_YKg3BAC4PovWVFKmDQaSw842I0hEXVylWwwjiBaEROEAOQx0A8PxCJloojbd0Uk8Wx9Us-kDvtCGRabZ8xMlw7prLGo7njb0SLjp8XYe71fmGbttV6I9fg82Z45kUe45coDbCDDW&amp;k=6LdtG3MUAAAAAEgAQNSUlyfVnm4sYfn19z5rL3TL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Sign Up_Midtrans/Page_MAP  Registration/iframe_concat(html1bodyclass, , scroll-able_5865ae</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq254CEQY9bu4WIGlwebnp06SWkVtvJ7rYHwfV3eTdb3lu3WualFDJKkrn9a01KM_YKg3BAC4PovWVFKmDQaSw842I0hEXVylWwwjiBaEROEAOQx0A8PxCJloojbd0Uk8Wx9Us-kDvtCGRabZ8xMlw7prLGo7njb0SLjp8XYe71fmGbttV6I9fg82Z45kUe45coDbCDDW&amp;k=6LdtG3MUAAAAAEgAQNSUlyfVnm4sYfn19z5rL3TL')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
