<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_VerifikasiImage</name>
   <tag></tag>
   <elementGuidId>cfeaa8c5-7f2e-4ea9-a446-065220d2ef18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27wV18Q3BVSz5J-ddKvG35J3fnJv0lszcSJtRP71eSUlY4lLXE5aOimeTpViexBf--1H1VOnjQAwCkQdKY6JfymDYeDPzJlnkqh7BIaaJteiGUe__qiGE4DVTeOQkgjgztb72qzyKjodNozA_rVJMYGqYP-NCiZWiOANMocX9f0sPJms_t0PCKk4EA1cVDUPPPqpKr8&amp;k=6LdtG3MUAAAAAEgAQNSUlyfVnm4sYfn19z5rL3TL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Sign Up_Midtrans/Page_MAP  Registration/iframe_concat(html1bodyclass, , scroll-able_e319a6</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27wV18Q3BVSz5J-ddKvG35J3fnJv0lszcSJtRP71eSUlY4lLXE5aOimeTpViexBf--1H1VOnjQAwCkQdKY6JfymDYeDPzJlnkqh7BIaaJteiGUe__qiGE4DVTeOQkgjgztb72qzyKjodNozA_rVJMYGqYP-NCiZWiOANMocX9f0sPJms_t0PCKk4EA1cVDUPPPqpKr8&amp;k=6LdtG3MUAAAAAEgAQNSUlyfVnm4sYfn19z5rL3TL')])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
